### ISSUE TITLE
Error when loading default boilerplate.html

### ISSUE THREAD

**Issue by HackingM** [twitwi/deck.js#9]
Hi,

I have downloaded your repository however when I load boilerplate.html I receive the following error:

> 'options.snippets.goto' is true but a .goto-form has been found.
> This might cause interaction glitches.
> 
> Suggestion: remove your html snippet or pass the {snippets: {goto: false}} option.

I am using Gentoo Linux, Gnome and Firefox 31.5.3.  If you need any more info please let me know.

Thanks!

**Comment by twitwi** [comment]
(Sorry, I missed this issue because of too many notifications from github...)

This message is due to my version of the goto extensions (that manages what happens when 'g' is pressed): it automatically adds the "goto" UI to limits the minimal amount of html to put in a presentation. (commit ref https://github.com/twitwi/deck.js/commit/6700c3ed85283f5f0e9edf4e366a0956f6d4f129 )

The `boilerplate.html` is actually from the bare deck.js (and contains the "goto" UI) and I should remove or fix it in this repository to avoid confusion.
Thanks.
